

int main() {

int a;




try
{
    a = 5;
}
catch ( Exception ex )
{
    return -1;
}



return 0;
}

